### ISSUE TITLE
Does not detect current Firefox from HKEY_CURRENT_USER

### ISSUE THREAD

**Issue by mccreery** [mozilla/node-fx-runner#73]
I came across this issue while investigating mozilla/web-ext#2201, and it seems to be the root cause.

Recent verisons of Firefox seem to install their registry keys in `HKEY_CURRENT_USER`. However node-fx-runner [only looks under `HKEY_LOCAL_MACHINE`](https://github.com/mozilla/node-fx-runner/blob/master/lib/utils.js#L87-L112), where in my case a much older version of Firefox (that does not exist) is referenced. This causes a file not found crash. I am not sure if Firefox *always* uses HKCU now or if it depends on the machine or installation process.

Output of `fx-runner start`: [error.txt](https://github.com/mozilla/node-fx-runner/files/6144945/error.txt)

## Keys under `HKEY_LOCAL_MACHINE`
```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Mozilla Firefox]
@="55.0.3"
"CurrentVersion"="55.0.3 (x64 en-GB)"

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Mozilla Firefox\55.0.3 (x64 en-GB)]
@="55.0.3 (x64 en-GB)"

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Mozilla Firefox\55.0.3 (x64 en-GB)\Main]
"Install Directory"="C:\\Users\\Sam\\AppData\\Local\\Mozilla Firefox"
"PathToExe"="C:\\Users\\Sam\\AppData\\Local\\Mozilla Firefox\\firefox.exe"

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Mozilla Firefox\55.0.3 (x64 en-GB)\Uninstall]
"Description"="Mozilla Firefox 55.0.3 (x64 en-GB)"
```
## Keys under `HKEY_CURRENT_USER`
```reg
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Mozilla\Mozilla Firefox]
@="86.0.1"
"CurrentVersion"="86.0.1 (x64 en-GB)"

[HKEY_CURRENT_USER\Software\Mozilla\Mozilla Firefox\86.0.1 (x64 en-GB)]
@="86.0.1 (x64 en-GB)"

[HKEY_CURRENT_USER\Software\Mozilla\Mozilla Firefox\86.0.1 (x64 en-GB)\Main]
"Install Directory"="E:\\Users\\Sam\\AppData\\Local\\Mozilla Firefox"
"PathToExe"="E:\\Users\\Sam\\AppData\\Local\\Mozilla Firefox\\firefox.exe"

[HKEY_CURRENT_USER\Software\Mozilla\Mozilla Firefox\86.0.1 (x64 en-GB)\Uninstall]
"Description"="Mozilla Firefox 86.0.1 (x64 en-GB)"
```
Although the values are very similar, notice the version difference between 86.0.1 and 55.0.3, which is 3 years older. My user folder is on the `E:\` drive so the old path no longer works.

**Comment by Rob--W** [comment]
Thanks for your investigation and write-up. It looks like the references node-fx-runner code predates the Firefox version by a few years: https://github.com/mozilla/node-fx-runner/blame/f1f0358073f74fbdf81caee2643ff2a9e7a25b99/lib/utils.js#L87-L112

I guess that it makes sense to update node-fx-runner to try HKCU before HKLM (assuming that Windows looks up HKCU before HKLM, I'm not sure whether that happens in practice but guess that it makes sense).

Are you interested in contributing a patch?

**Comment by mccreery** [comment]
I did make [an attempt](https://github.com/mccreery/node-fx-runner/commit/c04789d72f491eff640fe2bb4d0bd479625b8588) at patching the issue, but I must admit I am not mainly a JS developer and I'm not very familiar with the older implementation of promises used here. Feel free to let me know if I'm on the right track.

**Comment by Rob--W** [comment]
@mccreery Could you open a pull request? That's easier to review.
